# -*- coding: utf-8 -*-
"""Algorithmic Trading Strategy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CObsIC_x6Ix61p7sDz18GbBj26p34PJv
"""

#Description: This program uses the three moving average crossover strategy to determine when to buy and sell stock

#Import the libraries 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
plt.style.use('fivethirtyeight')

#Load the data
from google.colab import files 
uploaded = files.upload()

#Store the data into a variable 
df = pd.read_csv('TSLA.csv')

#Set the index
df = df.set_index(pd.DatetimeIndex(df['Date'].values))
df

#Visually show the close price 
plt.figure(figsize=(12.2, 4.5))
plt.title ('Close Price')
plt.plot(df['Close'])
plt.xlabel('Date', fontsize= 18)
plt.ylabel('Close Price', fontsize = 18)
plt.show()

#Calculate the three moving average
#Calculate the short/ fast exponential moving average 
shortEMA = df.Close.ewm(span = 5, adjust =  False).mean()
#Calculate the middle/medium exponential moving average 
MiddleEMA = df.Close.ewm(span=21, adjust = False).mean()
#Calculate the long/slow exponential moving average 
LongEMA = df.Close.ewm(span = 63, adjust = False).mean()

#Visualize the closing price andd the exponentgial moving averages
plt.figure(figsize=(12.2, 4.5))
plt.title ('Close Price')
plt.plot(df['Close'], label= 'Close Price', color = 'blue')
plt.plot(shortEMA, label = 'Short/Fast EMA', color = 'red')
plt.plot(MiddleEMA, label =  'Middle/medium EMA', color = 'orange')
plt.plot(LongEMA, label = 'Long/Slow EMA', color = 'green')
plt.xlabel('Date', fontsize= 18)
plt.ylabel('Close Price', fontsize = 18)
plt.show()

#Add the exponential moving averages to the dataset 
df['Short'] = shortEMA
df['Middle'] = MiddleEMA
df ['Long'] = Long

#Show the data 
df

