# -*- coding: utf-8 -*-
"""Candlestick_Charts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSA5d6K5tWKomTkeEYYxSwSArPTL_i_i
"""

#This program shows how to creare an interactive candlestick chart

import plotly.graph_objects as go 
import pandas as pd

#Load the stock data 
from google.colab import files 
uploaded = files.upload()

#Store the data into a data frame 
df = pd.read_csv('googl.csv')

#Show the data 
df

df = df.set_index(pd.DatetimeIndex(df['Date'].values))

#Show the data 
df

#Create an interactive candlestick chart 
figure = go.Figure(
    data = [
            go.Candlestick(
                x = df.index, 
                low = df['Low'],
                high = df['High'],
                close = df['Close'],
                open = df['Open'],
                increasing_line_color = 'red',
                decreasing_line_color = 'orange'
            )
    ]
)
figure.show()